

services:
  webdev:
    image: node:alpine
    volumes:
      - ./app:/app
      - ./scripts:/scripts
    ports:
      - "8080:8080"
    working_dir: /app
    command: sh -c "npm install -g http-server && http-server -p 8080"
    restart: unless-stopped

  sync:
    image: alpine
    volumes:
      - ./app:/app
      - ./scripts:/scripts
      - ~/.ssh:/root/.ssh:ro
    command: sh -c "apk add --no-cache openssh-client rsync && tail -f /dev/null"
